### ISSUE TITLE
Causes deadlock on newer versions on IntelliJ

### ISSUE THREAD

**Issue by mtraynham** [MaTriXy/restclient-idea-plugin#3]
Idea was failing to start for me.  Tracked it down to this.
# Found one Java-level deadlock:

"ApplicationImpl pooled thread 1":
  waiting to lock monitor 0x00007f83acbb30c8 (object 0x00000000a9ab9398, a java.awt.Component$AWTTreeLock),
  which is held by "AWT-EventQueue-0 16.0#IU-144.3600.7 IDEA, eap:true, os:Linux 3.19.0-32-generic, java-version:JetBrains s.r.o 1.8.0_76-release-b17"
"AWT-EventQueue-0 16.0#IU-144.3600.7 IDEA, eap:true, os:Linux 3.19.0-32-generic, java-version:JetBrains s.r.o 1.8.0_76-release-b17":
  waiting to lock monitor 0x00007f83acbb0158 (object 0x00000000ae325018, a java.lang.Object),
  which is held by "ApplicationImpl pooled thread 1"
# Java stack information for the threads listed above:

"ApplicationImpl pooled thread 1":
    at java.awt.Component.setFont(Component.java:1894)
    - waiting to lock <0x00000000a9ab9398> (a java.awt.Component$AWTTreeLock)
    at java.awt.Container.setFont(Container.java:1750)
    at javax.swing.JComponent.setFont(JComponent.java:2754)
    at javax.swing.LookAndFeel.installColorsAndFont(LookAndFeel.java:208)
    at javax.swing.plaf.basic.BasicPopupMenuUI.installDefaults(BasicPopupMenuUI.java:103)
    at javax.swing.plaf.basic.BasicPopupMenuUI.installUI(BasicPopupMenuUI.java:91)
    at javax.swing.JComponent.setUI(JComponent.java:666)
    at javax.swing.JPopupMenu.setUI(JPopupMenu.java:219)
    at javax.swing.JPopupMenu.updateUI(JPopupMenu.java:228)
    at javax.swing.JPopupMenu.<init>(JPopupMenu.java:193)
    at javax.swing.JPopupMenu.<init>(JPopupMenu.java:178)
    at com.sourcestream.plugin.idea.restclient.HelpMenuAction.<init>(HelpMenuAction.java:44)

**Comment by nicity** [comment]
Also https://youtrack.jetbrains.com/issue/IDEA-153408 :
"ApplicationImpl pooled thread 5" prio=0 tid=0x0 nid=0x0 blocked
     java.lang.Thread.State: BLOCKED
 on java.awt.Component$AWTTreeLock@595e9028 owned by "AWT-EventQueue-0 2016.1#IU-145.258.11 IDEA, eap:false, os:Linux 4.2.0-35-generic, java-version:JetBrains s.r.o 1.8.0_76-release-b18" Id=26
    at java.awt.Component.setFont(Component.java:1894)
    at java.awt.Container.setFont(Container.java:1750)
    at javax.swing.JComponent.setFont(JComponent.java:2754)
    at javax.swing.LookAndFeel.installColorsAndFont(LookAndFeel.java:208)
    at javax.swing.plaf.basic.BasicPopupMenuUI.installDefaults(BasicPopupMenuUI.java:103)
    at javax.swing.plaf.basic.BasicPopupMenuUI.installUI(BasicPopupMenuUI.java:91)
    at javax.swing.JComponent.setUI(JComponent.java:666)
    at javax.swing.JPopupMenu.setUI(JPopupMenu.java:219)
    at javax.swing.JPopupMenu.updateUI(JPopupMenu.java:228)
    at javax.swing.JPopupMenu.<init>(JPopupMenu.java:193)
    at javax.swing.JPopupMenu.<init>(JPopupMenu.java:178)
    at com.sourcestream.plugin.idea.restclient.FileMenuAction.<init>(FileMenuAction.java:44)
